excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
variable_name:
  min_length:
    warning: 0
large_tuple:
  warning: 6
function_body_length:
  warning: 70
line_length:
  ignores_comments: true
disabled_rules:
  - todo
